"""add author to book

Revision ID: 426471329e1a
Revises: aa03a1295020
Create Date: 2024-10-25 02:11:46.798551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426471329e1a'
down_revision = 'aa03a1295020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
